jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code Plugin\n\n"
  numExecutors: 5
  scmCheckoutRetryCount: 2
  mode: NORMAL
  clouds:
  - hypervisor:
      hypervisorHost: "localhost"
      hypervisorSshPort: 22
      hypervisorSystemUrl: "system?no_tty=1"
      hypervisorType: "QEMU"
      maxOnlineSlaves: 1
      useNativeJavaConnection: true
      username: "nekrad"
  - hypervisor:
      hypervisorHost: "localhost"
      hypervisorSshPort: 22
      hypervisorSystemUrl: "system?no_tty=1"
      hypervisorType: "R4D"
      maxOnlineSlaves: 3
      useNativeJavaConnection: true
      username: "nekrad"
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "unix:///var/run/docker.sock"
        readTimeout: 60
      name: "docker"
      templates:
      - connector:
          attach:
            user: "jenkins"
        dockerTemplateBase:
          image: "jenkins-slave-kernel"
        labelString: "kernel"
        name: "DNG kernel build image"
#        pullStrategy: PULL_ALWAYS
        pullTimeout: 300
        remoteFs: "/home/jenkins"

#  nodes:
#    - dumb:
#        labelString: "linux docker test kernel"
#        name: "(master)"

jobs:
  - script: >
      multibranchPipelineJob('CIRT-test') {
          branchSources {
              git {
                  id = 'cirt-test'
                  remote('https://github.com/ci-rt/test-description.git')
              }
          }
      }

unclassified:
  globalLibraries:
    libraries:
      - name: "CI-RT"
        defaultVersion: origin/master
        retriever:
          modernSCM:
            scm:
              git:
                remote: "https://github.com/metux/jenkins-cirt-libs"
  location:
    adminAddress: "info@metux.net"
    url: "http://jenkins:8080/"

  mailer:
    adminAddress: info@metux.net
    replyToAddress: info@metux.net
    smtpHost: localhost
    smtpPort: 25

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "POSTGRES_CREDENTIALS"
            username: "jenkins"
            password: "jenkins001"
            description: "cirt postgres database"
