#!/bin/sh

# a simple script that can auto-detect the appropriate JAVA_HOME value
# based on whether the JDK or only the JRE is installed

set -e
dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"
